#!/usr/bin/env python3
"""
Builds a Windows installer
"""

import sys
import os
import subprocess
import re
from pathlib import Path


def get_project_root():
    """Get the project root directory (parent of scripts/)"""
    script_dir = Path(__file__).parent.absolute()
    return script_dir.parent


def get_version_from_file(project_root):
    """
    Read version from src/_version.py (generated by setuptools_scm)

    Args:
        project_root: Root directory of the project

    Returns:
        Version string or None if not found
    """
    version_file = project_root / "src" / "_version.py"

    if not version_file.exists():
        print(f"⚠ Warning: Version file not found: {version_file}")
        return None

    try:
        with open(version_file, 'r', encoding='utf-8') as f:
            content = f.read()

        # Look for __version__ = "x.y.z" or __version__ = 'x.y.z'
        match = re.search(r"__version__\s*=\s*version\s*=\s*['\"]([^'\"]+)['\"]", content)
        if match:
            version = match.group(1)
            print(f"✓ Found version: {version}")
            return version
        else:
            print(f"⚠ Warning: Could not parse version from {version_file}")
            return None

    except Exception as e:
        print(f"⚠ Warning: Error reading version file: {e}")
        return None


def find_inno_setup():
    """
    Find the Inno Setup compiler (ISCC.exe)

    Returns:
        Path to ISCC.exe or None if not found
    """
    # Common installation paths
    possible_paths = [
        r"C:\Program Files (x86)\Inno Setup 6\ISCC.exe",
        r"C:\Program Files\Inno Setup 6\ISCC.exe",
        r"C:\Program Files (x86)\Inno Setup 5\ISCC.exe",
        r"C:\Program Files\Inno Setup 5\ISCC.exe",
    ]

    for path in possible_paths:
        if os.path.exists(path):
            return path

    # Try to find in PATH
    try:
        result = subprocess.run(
            ["where", "ISCC.exe"],
            capture_output=True,
            text=True,
            check=False
        )
        if result.returncode == 0:
            return result.stdout.strip().split('\n')[0]
    except Exception:
        pass

    return None



def run_inno_setup(project_root, iscc_path, version=None):
    """
    Run Inno Setup to create the installer

    Args:
        project_root: Root directory of the project
        iscc_path: Path to ISCC.exe
        version: Version string to pass to Inno Setup (optional)

    Returns:
        True if successful, False otherwise
    """
    print("\n" + "="*70)
    print("STEP 2: Creating Installer")
    print("="*70 + "\n")

    iss_file = project_root / "installer.iss"

    if not iss_file.exists():
        print(f"✗ Error: Installer script not found: {iss_file}")
        return False

    print(f"Inno Setup Compiler: {iscc_path}")
    print(f"Installer Script: {iss_file}")
    if version:
        print(f"Version: {version}")

    try:
        # Build command with version parameter if provided
        cmd = [iscc_path]
        if version:
            # Pass version as a preprocessor define to Inno Setup
            cmd.append(f"/DMyAppVersion={version}")
        cmd.append(str(iss_file))

        result = subprocess.run(
            cmd,
            cwd=str(project_root),
            check=False
        )

        if result.returncode == 0:
            print("\n✓ Installer created successfully")
            return True
        else:
            print("\n✗ Installer creation failed")
            return False

    except Exception as e:
        print(f"\n✗ Error running Inno Setup: {e}")
        return False


def verify_output(project_root, version=None):
    """
    Verify that the installer was created

    Args:
        project_root: Root directory of the project
        version: Version string used in the filename (optional)

    Returns:
        True if installer exists, False otherwise
    """
    installer_dir = project_root / "build" / "installer"

    # Construct expected filename with version
    if version:
        installer_filename = f"moshi-connect-setup-{version}.exe"
    else:
        installer_filename = "moshi-connect-setup-0.0.0-dev.exe"

    installer_file = installer_dir / installer_filename

    # If the expected file doesn't exist, try to find any installer file
    if not installer_file.exists():
        # Look for any moshi-connect-setup-*.exe file
        if installer_dir.exists():
            installer_files = list(installer_dir.glob("moshi-connect-setup-*.exe"))
            if installer_files:
                installer_file = installer_files[0]
                print(f"\n⚠ Found installer with different name: {installer_file.name}")

    if installer_file.exists():
        size_mb = installer_file.stat().st_size / (1024 * 1024)
        print(f"\n✓ Installer created: {installer_file}")
        print(f"  Size: {size_mb:.2f} MB")
        return True
    else:
        print(f"\n✗ Installer not found: {installer_file}")
        return False


def main():
    print("Build Installer Script")
    print(f"Platform: {sys.platform}")
    print(f"Python: {sys.version}")

    # Check if running on Windows
    if sys.platform != "win32":
        print("\n✗ Error: This script is only for Windows")
        print("  The installer can only be built on Windows using Inno Setup")
        return 1

    # Get project root
    project_root = get_project_root()
    print(f"Project root: {project_root}")

    # Get version from _version.py
    print("\nReading version from git tags...")
    version = get_version_from_file(project_root)
    if not version:
        print("⚠ Warning: Using default version (0.0.0-dev)")
        print("  Run 'pip install -e .' to generate version from git tags")

    # Find Inno Setup
    print("\nSearching for Inno Setup...")
    iscc_path = find_inno_setup()

    if not iscc_path:
        print("\n✗ Error: Inno Setup not found")
        print("\nPlease install Inno Setup from: https://jrsoftware.org/isdl.php")
        print("After installation, run this script again.")
        return 1

    print(f"✓ Found Inno Setup: {iscc_path}")

    if not run_inno_setup(project_root, iscc_path, version):
        print("\n✗ Failed to create installer")
        return 1

    # Verify output
    if not verify_output(project_root, version):
        print("\n✗ Installer verification failed")
        return 1
    
    # Success summary
    print("\n" + "="*70)
    print("BUILD COMPLETE")
    print("="*70)
    print("\n✓ Installer created successfully")

    # Show installer filename with version
    if version:
        installer_filename = f"moshi-connect-setup-{version}.exe"
    else:
        installer_filename = "moshi-connect-setup-0.0.0-dev.exe"

    print("\nThe installer is ready for distribution:")
    print(f"  build\\installer\\{installer_filename}")
    print("\nNext steps:")
    print("1. Test the installer on a clean Windows machine")
    print("2. Verify that the service installs and starts correctly")
    print("3. Test the GUI application")
    print("4. Test the uninstaller")
    print("5. Distribute the installer to users")

    return 0


if __name__ == "__main__":
    sys.exit(main())

